### ISSUE TITLE
Rails for content admin?

### ISSUE THREAD

**Issue by pswoodworth** [Jumpshell/demo-admin#1]
We should evaluate rails and the rails admin as a platform for content management.

**Comment by pswoodworth** [comment]
Get rails admin to same level as current django admin

**Comment by chrisbolin** [comment]
RailsAdmin
- No html editor included. https://github.com/sferik/rails_admin/wiki/Wysihtml5
- Geo gem: https://github.com/beyondthestory/rails_admin_map_field
- Support for Postgres JSON
- 


Active Admin
- No html editor included. https://github.com/ejholmes/active_admin_editor
- No geo support -

**Comment by pswoodworth** [comment]
not great support, closing in favor of using Django
